--create table public.ideas
--(
--id bigint primary key,
--textt varchar,
--created_at timestamp default now(),
--is_actual bool default true
--);
--insert into public.ideas(id, textt)
--values (1 ,'Hello Nurinissa!'),
--(2 ,'Hello Said:))))')